In [3]:
import numpy as np
from sklearn import preprocessing #前処理用のパッケージ

In [4]:
input_data = np.array([[5.1,-2.9,3.3],
                                         [-1.2,7.8,-6.1],
                                         [3.9,0.4,2.1],
                                         [7.3,-9.9,-4.5]])

# 二値化

二値化とは、数値を０、１に変換することです。

Binarizer()を使って、闘値(threshold)を2.1として二値化する

2.1を超えると1になり、それ以外は０

In [13]:
data_binarized = preprocessing.Binarizer(threshold=2.1).transform(input_data)
print("Binarized data:\n",data_binarized)

Binarized data:
 [[1. 0. 1.]
 [0. 1. 0.]
 [1. 0. 0.]
 [1. 0. 0.]]


# 平均値を引く
メソッドmean()とstd()はそれぞれ、平均（Mean）と標準偏差（Std　deviation）を表す

In [14]:
print("BEFORE:")
print("Mean =",input_data.mean(axis=0))
print("Std deciation =",input_data.std(axis=0))

BEFORE:
Mean = [ 3.775 -1.15  -1.3  ]
Std deciation = [3.12039661 6.36651396 4.0620192 ]


scale()を使うと、平均値を引いてから、標準偏差が１になるようにスケーリング

In [19]:
data_scaled = preprocessing.scale(input_data)
print("AFTER:")
print("Mean =",data_scaled.mean(axis=0))
print("Std deciation =",data_scaled.std(axis=0))

AFTER:
Mean = [1.11022302e-16 0.00000000e+00 2.77555756e-17]
Std deciation = [1. 1. 1.]


# スケーリング

