In [1]:
import numpy as np

In [6]:
#ベクトル定義
a = np.array([1,2,3,4])
b = np.array([[4],[-1],[6]])
print(a)
print(b)

[1 2 3 4]
[[ 4]
 [-1]
 [ 6]]


In [8]:
#行列の定義
C = np.array([[3,-2],[7,1]])
C

array([[ 3, -2],
       [ 7,  1]])

In [11]:
D = np.array([[3,-2,0,1],[7,1,-1,2],[4,-5,1,3]])
D

array([[ 3, -2,  0,  1],
       [ 7,  1, -1,  2],
       [ 4, -5,  1,  3]])

In [21]:
#ベクトルの作成
a = np.zeros((1,2))
a

array([[0., 0.]])

In [23]:
b = np.ones((4,1))
b

array([[1.],
       [1.],
       [1.],
       [1.]])

In [29]:
#行列の作成
C = np.eye(3)
C

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [32]:
D = np.eye(3,4)
D

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.]])

In [37]:
# 基本情報の取得
a = np.array([2,3,4])
a

array([2, 3, 4])

In [42]:
B = np.array([[1.2,3.5,5.1],[-0.3,1.1,-4.5]])
B

array([[ 1.2,  3.5,  5.1],
       [-0.3,  1.1, -4.5]])

In [39]:
a.shape

(3,)

In [51]:
B.shape

(2, 3)

In [40]:
a.dtype

dtype('int64')

In [50]:
B.dtype

dtype('float64')

In [45]:
#次元
a.ndim

1

In [46]:
B.ndim

2

In [47]:
#要素数
a.size

3

In [49]:
B.size

6